### ISSUE TITLE
ERR: sprop-parameter-sets is missing (96 profile-level-id=4D0014;packetization-mode=0)

### ISSUE THREAD

**Issue by BenLocal** [aler9/gortsplib#88] opened 2021-11-20 08:50 UTC
In some rtsp stream, sdp may not have sps, pps data, it was passed in the NAULS data 

SDP：
```
      v=0
      o=- 1109162014219182 0 IN IP4 0.0.0.0
      s=HIK Media Server V3.5.43
      i=HIK Media Server Session Description : standard
      e=NONE
      c=IN IP4 0.0.0.0
      t=0 0
      a=control:*
      b=AS:2176
      a=range:npt=now-
      m=video 0 RTP/AVP 96
      i=Video Media
      a=rtpmap:96 H264/90000
      a=fmtp:96 profile-level-id=4D0014;packetization-mode=0
      a=control:trackID=video
      b=AS:2048
      m=audio 0 RTP/AVP 104
      i=Audio Media
      a=rtpmap:104 MPEG4-GENERIC/48000
      a=control:trackID=audio
      a=fmtp:104 streamtype=5;profile-level-id=15;mode=AAC-hbr;config=1190;SizeLength=13;IndexLength=3;IndexDeltaLength=3;Profile=1;
      b=AS:128
      a=Media_header:MEDIAINFO=494D4B4801010000040000010120011080BB000000F4010000000000000000000000000000000000;
      a=appversion:1.0
```

RTP NAULS：
sps: [103,77,0,42,150,53,64,240,4,79,203,55,1,1,1,64,0,1,194,0,0,87,228,1]
pps: [104,238,60,128]

**Comment by aler9** [comment] 2021-11-22 14:19
duplicate of https://github.com/aler9/rtsp-simple-server/issues/411

**Closed by aler9** 2021-11-22 14:19 UTC
