### ISSUE TITLE
Read raw video frames

### ISSUE THREAD

**Issue by amirzenoozi** [aler9/gortsplib#24] opened 2021-03-07 08:34 UTC
Hi, I Have A Little Problem With this package
I want to read just 3 frames and then close the connection how can I use `ReadFrames` in this scenario?
Thank u.

**Comment by aler9** [comment] 2021-03-10 21:57
Hello, i think you mean "video frames", but unfortunately the library doesn't decode video frames - video frames send with RTSP are

1. encoded with H264
2. wrapped in RTP/H264
3. wrapped in RTSP

The last two passages are indeed handled by the library, that is able to unwrap frames from RTSP and RTP/H264, but the library is not able to decode H264, there would also be licensing problems since the MPEG alliance usually scans the internet and demands a lot of money to people that decodes H264.

Anyway, to obtain H264 frames (that you have to find a way to decode, for instance with gstreamer), you can look here 

https://github.com/aler9/gortsplib/blob/main/examples/client-read-h264/main.go

**Comment by aler9** [comment] 2021-03-10 21:58
duplicate of #17

**Closed by aler9** 2021-03-10 21:58 UTC
